services:
  postgres:
    image: postgres:15-alpine # Choose latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db_name # Db name
      POSTGRES_HOST_METHOD: trust

  backend:
    build: .
    ports:
      - 8000:8000
      - 9229:9229 # For debugging
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.pnpm-store
      - /usr/src/app/node_modules
    command: pnpm start:docker
    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgres://postgres@postgres/db_name # Db setup
      PORT: 8000
