services:
  backend:
    build: .
    ports:
      - 8000:8000
      - 9229:9229 # For debugging
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.pnpm-store
      - /usr/src/app/node_modules
    command: pnpm start:docker

    environment:
      PORT: 8000
